spring:
  redis:
    database: 9
    host: 192.168.132.128
    port: 6666
    password: 123456
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 1000ms
